name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - run: dotnet restore CloudsoftJob.sln
      - run: dotnet build CloudsoftJob.sln --no-restore
      - run: dotnet test CloudsoftJob.sln --no-build --no-restore
